name: Windows RDP
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath C:\ngrok
          
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin Nuvex@12345

      - name: Start Ngrok
        run: |
          C:\ngrok\ngrok.exe authtoken 3B1evhpe6OvmZZuS9SxBX9x8URO_wcUeHeT694y3P1aBhN46
          C:\ngrok\ngrok.exe tcp 3389
